### ISSUE TITLE
ESP32 Reset

### ISSUE THREAD

**Issue by Tjeerdm** [DanD222/sensorboard_NewHardware#1]
The ESP32 reset line (EN) needs a capacitor to ground.
See https://www.espressif.com/sites/default/files/documentation/esp32-s2-wroom_esp32-s2-wroom-i_datasheet_en.pdf
Figure 6.

**Comment by DanD222** [comment]
Thanks - fixed with 91d300ca74186b6ae7525fd264037ecde7ab9f06 and 641f369897ab1e9f81edeb3a6cbcbd9e41f9a276.
