### ISSUE TITLE
GPIO45 and GPIO46

### ISSUE THREAD

**Issue by Tjeerdm** [DanD222/sensorboard_NewHardware#3]
These are mode strapping inputs on power-up. GPIO45 changes the power supply voltage for the SPI ROM.
GPIO46 influences the boot mode.
I think they should not be used when not absolutely necessary.

Thats it for the time being :-) Have a nice weekend.

Tjeerd Mulder

**Comment by DanD222** [comment]
Awesome, thakns for the input Tjeerd!
